name: tests
on: [workflow_call]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Starting dependent containers for testing
        run: docker-compose up -d
      - name: Wait for containers to be up and running
        run: bash waitForContainerSetup.sh
      - name: Setup s3
        run: bash setupS3Env.sh
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

